doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DEFAULT_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
            customer:
                url: '%env(resolve:CUSTOMER_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine/common'
                        prefix: 'App\Domain\Company'
                        alias: Main
            customer:
                connection: customer
                mappings:
                    Customer:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine/customer'
                        prefix: 'App\Domain'
                        alias: Customer