doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DEFAULT_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
            crm:
                url: '%env(resolve:CRM_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
                wrapper_class: App\Infrastructure\Persistence\Doctrine\DynamicDatabase

        types:
            email_address:
                class: App\Infrastructure\Persistence\Doctrine\Types\EmailAddressType
            array_email_address:
                class: App\Infrastructure\Persistence\Doctrine\Types\ArrayEmailAddressType
            nif:
                class: App\Infrastructure\Persistence\Doctrine\Types\NIFType
            password:
                class: App\Infrastructure\Persistence\Doctrine\Types\PasswordType
            url:
                class: App\Infrastructure\Persistence\Doctrine\Types\URLType

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Landing:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/Landing'
                        prefix: 'App\Domain'
            crm:
                connection: crm
                mappings:
                    CRM:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping/CRM'
                        prefix: 'App\Domain'