doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DEFAULT_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4
            crm:
                url: '%env(resolve:CRM_DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '8.0'
                charset: utf8mb4

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Company:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine/common'
                        prefix: 'App\Domain'
            crm:
                connection: crm
                mappings:
                    CRM:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine/crm'
                        prefix: 'App\Domain'
                    Security:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/packages/doctrine/security'
                        prefix: 'App\Infrastructure\Symfony\Security'