security:
    encoders:
        App\Domain\Customer\Customer:
            algorithm: auto
        App\Domain\Employee\Employee:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        customer_provider:
            id: App\Infrastructure\Symfony\Security\CustomerUserProvider
        employee_provider:
            id: App\Infrastructure\Symfony\Security\EmployeeUserProvider
        all_users:
            chain:
                providers: ['customer_provider', 'employee_provider']
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            provider: all_users
            guard:
                authenticators:
                    - App\Infrastructure\Symfony\Security\Authenticator
                    - App\Infrastructure\Symfony\Security\CustomerAuthenticator
                entry_point: App\Infrastructure\Symfony\Security\Authenticator
            logout:
                path: crm_logout
                # where to redirect after logout
                target: crm_login

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:

        - { path: '^/crm/manager',  roles: ROLE_MANAGER }
        - { path: '^/crm/worker',   roles: ROLE_MANAGER }
        - { path: '^/crm/category', roles: ROLE_MANAGER }
        - { path: '^/crm/activity', roles: ROLE_WORKER }
        - { path: '^/crm/customer', roles: ROLE_WORKER }
        - { path: '^/crm/familiar/create', roles: ROLE_WORKER }
        - { path: '^/crm/familiar/{nif}/edit', roles: ROLE_WORKER }
        - { path: '^/crm/familiar/{nif}/email', roles: ROLE_WORKER }
        - { path: '^/crm/familiar', roles: ROLE_USER }
        - { path: '^/crm',          roles: ROLE_USER }
