version: '3.7'

services:

  web:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - php
      - db
      - redis

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      XDEBUG_CONFIG: remote_host=10.254.254.254
      PHP_IDE_CONFIG: "serverName=localhost"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
      - ./.docker/php/conf.d/:/usr/local/etc/php/conf.d/
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'tfg_default'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge