crm_dashboard:
  path: /crm
  controller: App\Infrastructure\Symfony\Controller\CRM\DashboardController::view

crm_login:
  path: /crm/login
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Login\LoginGetController::view

crm_login_post:
  path: /crm/login
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Login\LoginPostController::view

crm_forgot-password:
  path: /crm/forgot-password
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordGetController::view

crm_forgot-password_post:
  path: /crm/forgot-password
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordPostController::view

crm_manager_list:
  path: /crm/manager
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\ListGetController::view

crm_worker_list:
  path: /crm/worker
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Worker\ListGetController::view

crm_customer_list:
  path: /crm/customer
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Customer\ListGetController::view

crm_familiar_list:
  path: /crm/familiar
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\ListGetController::view