crm_dashboard:
  path: /crm
  controller: App\Infrastructure\Symfony\Controller\CRM\DashboardController::view

crm_error:
  path: /crm/error
  controller: App\Infrastructure\Symfony\Controller\CRM\ErrorController::view

login:
  resource: 'crm/login.yaml'

category:
  resource: 'crm/category.yaml'

manager:
  resource: 'crm/manager.yaml'

worker:
  resource: 'crm/worker.yaml'

customer:
  resource: 'crm/customer.yaml'

familiar:
  resource: 'crm/familiar.yaml'