---
-
  name: Provision Servers
  hosts: all
  gather_facts: yes
  roles:
    - { role: nginx,  tags: ['frontal'] }
    - { role: php,    tags: ['frontal'] }
    - { role: mysql,  tags: ['mysql'] }
    - { role: redis,  tags: ['redis'] }
    - { role: git,    tags: ['git'] }
    - { role: system, tags: ['system'] }
    - { role: yarn,   tags: ['yarn'] }
