---
-
  name: Provision Servers
  hosts: all
  gather_facts: yes
  roles:
    - { role: nginx, tags: ['frontal'] }
    - { role: geerlingguy.mysql, tags: ['mysql'], become: yes }
    - { role: mysql, tags: ['mysql'] }
    - { role: php, tags: ['frontal'] }
