---
- include_role:
    name: geerlingguy.mysql
  vars:
    ansible_become: yes

- name: enable mysql
  service:
    name: mysqld
    state: restarted
    enabled: yes
  become: true

- name: copy the .my.cnf config
  template:
    src: .my.cnf.j2
    dest: ~/.my.cnf

- name: create mysql client user
  mysql_user:
      login_user: "{{ mysql_root_user }}"
      login_password: "{{ mysql_root_password }}"
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: '*.*:ALL,GRANT'
      state: present
      host: '%'

- name: create default database
  mysql_db:
    name: tfg_default
    state: present