crm:
  resource: 'routes/crm.yaml'

error:
  path: /error
  controller: App\Infrastructure\Symfony\Controller\Landing\ErrorController::view

sign_in:
  path: /signin
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\SignIn\SignInGetController::view

sign_in_post:
  path: /signin
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\SignIn\SignInPostController::view

register:
  path: /register
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterGetController::view

register_post:
  path: /register
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterPostController::view

index:
  path: /
  controller: App\Infrastructure\Symfony\Controller\Landing\HomeController::view
