crm_dashboard:
  path: /crm
  controller: App\Infrastructure\Symfony\Controller\CRM\DashboardController::view

crm_login:
  path: /crm/login
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Login\LoginGetController::view

crm_login_post:
  path: /crm/login
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Login\LoginPostController::view

crm_forgot-password:
  path: /crm/forgot-password
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordGetController::view

crm_forgot-password_post:
  path: /crm/forgot-password
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordPostController::view

error:
  path: /error
  controller: App\Infrastructure\Symfony\Controller\Landing\ErrorController::view

sign_in:
  path: /signin
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\SignIn\SignInGetController::view

sign_in_post:
  path: /signin
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\SignIn\SignInPostController::view

register:
  path: /register
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterGetController::view

register_post:
  path: /register
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterPostController::view

index:
  path: /
  controller: App\Infrastructure\Symfony\Controller\Landing\HomeController::view
