index:
  path: /
  controller: App\Infrastructure\Symfony\Controller\Landing\HomeController::view

error:
  path: /error
  controller: App\Infrastructure\Symfony\Controller\Landing\ErrorController::view

register:
  path: /register
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterGetController::view

register_post:
    path: /register
    methods: POST
    controller: App\Infrastructure\Symfony\Controller\Landing\Register\RegisterPostController::view

login:
  path: /login
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\Login\LoginGetController::view

login_post:
  path: /login
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\Login\LoginPostController::view

forgot-password:
  path: /forgot-password
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\Landing\ForgotPassword\ForgotPasswordGetController::view

forgot-password_post:
  path: /forgot-password
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\Landing\ForgotPassword\ForgotPasswordPostController::view

dashboard:
    path: /crm/dashboard
    methods: GET
    controller: App\Infrastructure\Symfony\Controller\CRM\DashboardController::view
