App\Management\Company\Domain\Company:
  type: entity
  repositoryClass: App\Management\Company\Infrastructure\Persistence\Doctrine\DoctrineCompanyRepository
  table: companies
  schema: tfg_default # The schema the table lies in, for platforms that support schemas (Optional, >= 2.5)
  readOnly: flase
  indexes:
    name_index:
      columns: [ namespace ]
  id:
    namespace:
      type: string
  fields:
    name:
      type: string
      length: 150
    email:
      type: string
      length: 150
      unique: true