App\Domain\Familiar\Familiar:
  type: entity
  repositoryClass: App\Infrastructure\Persistence\Doctrine\DoctrineFamiliarRepository
  table: familiars
  schema: tfg_example
  readOnly: flase
  id:
    nif:
      type: string
  fields:
    name:
      type: string
      length: 150
    surname:
      type: string
      length: 150
    birthday:
      type: date
    portrait:
      type: string
      length: 300