---
- name: ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: true

- name: start nginx
  service:
    name: nginx
    state: started
  become: true

- name: copy the nginx config file and restart nginx
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  become: true