---
- name: Delete dev files and folders
  file:
      path: "{{ansistrano_release_path.stdout}}/{{ item }}"
      state: absent
  with_items:
      - .docker
      - .idea
      - etc
      - tests
      - composer.json
      - composer.lock
      - docker-compose.yml
      - Makefile
      - .env
      - .env.test
      - .gitignore
      - infection.json.dist
      - package.json
      - package-lock.json
      - phpunit.xml.dist
      - Readme.md
      - symfony.lock
      - webpack.config.js
      - yarn.lock

- name: Change log folder owner to www-data
  become: yes
  file:
    dest: "{{ansistrano_release_path.stdout}}/var/log"
    mode: u=rwX,g=rwX,o=rwX
    recurse: yes
    state: directory
