crm_category_list:
  path: /crm/category
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\ListGetController::view

crm_category_create:
  path: /crm/category/create
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\CreateGetController::view

crm_category_create_post:
  path: /crm/category/create
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\CreatePostController::view

crm_category_edit:
  path: /crm/category/{id}/edit
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\EditGetController::view

crm_category_edit_post:
  path: /crm/category/{id}/edit
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\EditPostController::view

crm_category_delete:
  path: /crm/category/{id}/delete
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Category\DeleteGetController::view