crm_familiar_list:
  path: /crm/familiar
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\ListGetController::view

crm_familiar_create:
  path: /crm/familiar/create
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\CreateGetController::view

crm_familiar_create_post:
  path: /crm/familiar/create
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\CreatePostController::view

crm_familiar_edit:
  path: /crm/familiar/{nif}/edit
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\EditGetController::view

crm_familiar_edit_post:
  path: /crm/familiar/{nif}/edit
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\EditPostController::view

crm_familiar_view:
  path: /crm/familiar/{nif}
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\ViewGetController::view

crm_familiar_delete:
  path: /crm/familiar/{nif}/delete
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\DeleteGetController::view

## Actions

crm_familiar_send_email:
  path: /crm/familiar/{nif}/email
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\SendEmailGetController::view

crm_familiar_send_email_post:
  path: /crm/familiar/{nif}/email
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\SendEmailPostController::view

crm_familiar_link_activity:
  path: /crm/familiar/{nif}/activity
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\LinkActivityGetController::view

crm_familiar_link_activity_post:
  path: /crm/familiar/{nif}/activity
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\LinkActivityPostController::view

crm_familiar_link_activity_delete:
  path: /crm/familiar/{nif}/activity/{id}/delete
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\DeleteLinkActivityGetController::view

crm_familiar_add_note:
  path: /crm/familiar/{nif}/note
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\AddNoteGetController::view

crm_familiar_add_note_post:
  path: /crm/familiar/{nif}/note
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\AddNotePostController::view

crm_familiar_calendar:
  path: /crm/familiar/{nif}/calendar
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\CalendarGetController::view

crm_familiar_calendar_events:
  path: /crm/familiar/{nif}/calendar/events
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Familiar\Action\CalendarEventsGetController::view