crm_login:
  path: /login
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Login\LoginGetController::view

crm_login_post:
  path: /login
  methods: POST

crm_forgot-password:
  path: /forgot-password
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordGetController::view

crm_forgot-password_post:
  path: /forgot-password
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\ForgotPassword\ForgotPasswordPostController::view
