crm_manager_list:
  path: /crm/manager
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\ListGetController::view

crm_manager_create:
  path: /crm/manager/create
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\CreateGetController::view

crm_manager_create_post:
  path: /crm/manager/create
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\CreatePostController::view

crm_manager_edit:
  path: /crm/manager/{nif}/edit
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\EditGetController::view

crm_manager_edit_post:
  path: /crm/manager/{nif}/edit
  methods: POST
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\EditPostController::view

crm_manager_view:
  path: /crm/manager/{nif}
  methods: GET
  controller: App\Infrastructure\Symfony\Controller\CRM\Manager\ViewGetController::view